name: CV-build

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: html to pdf
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./index.html
          outputFile: ./cv.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "CV"
          files: ./cv.pdf