name: CV-build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: html to pdf
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./index.html
          outputFile: ./cv.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
      - run: ls
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./cv.pdf"
          token: ${{ secrets.TOKEN }}
          tag: "CV"